### PR TITLE
Issue -690 Feature to take author to content fragment edit options fr…

### PR DESCRIPTION
**Pull request by surya057**
…om template level.

### CODE REVIEW

**Comment by surya057** [comment]
Hi, This seems like a dependency issue. Can someone point me the right direction, please?

**Comment by surya057** [comment]
Hi Team, Can someone review and approve this PR, please?.

**Comment by msagolj** [comment]
@surya057  Are you aware that there is already a button for editing the content fragment in the toolbar ?

image

There is none for the content fragment list (not sure it makes much sense to add one there). If that's what you intend to do it should be added in the core components project, not here in the example project. This example project is showing of features of AEM that exist in the product.

**Comment by surya057** [comment]
Thank you, For pointing it out. It is for content fragment list component. We are using plenty of content fragment list component so it is difficult to search for the proper content fragment group under content/dam path.

Sure, will add it to core components.

**Comment by msagolj** [comment]
@surya057 ok , thank you for the update. So i will close this one an you can create a new PR in the core components project

**Pull request closed without merging**
